### PR TITLE
Added 5 Basic Python Practice Program

### PR DESCRIPTION
**Pull request by Anamaya1729**
## First Testing PR
This is my first Pull Request so please let me know if are these okay? and can I Contribute more? 

## Description
I tried to follow pep8 styling guide in writing them and kept the code as simple and readable as possible.

### CODE REVIEW

**Comment by sj5027052** [comment]
> ## First Testing PR
> This is my first Pull Request so please let me know if are these okay? and can I Contribute more?
> 
> ## Description
> I tried to follow pep8 styling guide in writing them and kept the code as simple and readable as possible.

Thanks for Contributing, but contribution to this Project will only be considered from October 1 to October 31 as this is the Part of Hactober fest 2022

**Comment by Anamaya1729** [comment]
Ohh okay, thanks for letting me know. Should I leave the PR as it is or remove it?

**Comment by sj5027052** [comment]
> Ohh okay, thanks for letting me know. Should I leave the PR as it is or remove it?

for now close it and comeback after 1 october and again open a new Pr then surely it will be merged

**Comment by Anamaya1729** [comment]
Okay thanks a lot!

**Pull request closed without merging**
